### ISSUE TITLE
Tune STOMP.js WebSocket heartbeat intervals?

### ISSUE THREAD

**Issue by valeriansaliou** [rsauget/flexom-lib#32]
Hello there,

Just figured out that homebridge-flexom, which relies on flexom-lib, sends/receives frequent pings/pongs from the Hemis WS endpoint. Currently the interval for both c2s and s2s are set to 5s.

Also, the reconnect delay is set to 100ms, which I'm afraid could trigger a flood of connection attempts if the WS server goes down for a few seconds. Which could lead to the target WS server implementing restrictive rate-limits if there are too many homebridge-flexom clients flooding when it goes back online.

Ref: https://github.com/rsauget/flexom-lib/blob/master/src/hemis/ws.ts#L36

Is that necessary? Could all intervals be made larger?

Here's what I'd suggest, based on working w/ WS servers in different networking environments (eg. w/ restrictive NATs killing long-running TCP connections that do not heartbeat frequently-enough):

```
    reconnectDelay: 1000,
    heartbeatIncoming: 20000,
    heartbeatOutgoing: 20000,
```

This changes `reconnectDelay` from 100ms to 1s, `heartbeatOutgoing ` + `heartbeatIncoming` from 5s to 20s.

**Comment by rsauget** [comment]
Thanks @valeriansaliou, I don't have your experience using websockets, so I'm gonna trust you on this one (I also went through some docs & articles and it seems sensible) 👍
